config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'guides#index', as: :guides

  # Models
  get 'guides/basics'
  get 'guides/migrations'
  get 'guides/validations'
  get 'guides/callbacks'
  get 'guides/associations'
  get 'guides/interface'
  get 'guides/abasics'

  # Views
  get 'guides/viewover'
  get 'guides/layrender'
  get 'guides/viewform'

  # Controllers
  get 'guides/rrout'
  get 'guides/ocontroller'

  resources :books do
    resources :comments, only: [ :create ]
  end

  resources :authors
  resources :articles

  #get 'account', to: 'accounts#show'
  resource :account

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, :text, presence: true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :comments
  validates :title, presence: true
  validates :description, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one :account
  has_many :articles

  after_create :create_account

  def gold
    self.account.gold
  end

  def silver
    self.account.silver
  end

  def wood
    self.account.wood
  end

  def name
    self.account.name
  end

  private
    def create_account
      self.account = Account.new(gold:300,silver:200,wood:100)
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
    @account = current_user.account
  end

  def update
    @account = current_user.account
    if(@account.update(account_params))
      redirect_to account_path
    else
      render 'edit'
    end
  end

  private
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.create(article_params)
    if(@article.valid?)
      redirect_to articles_path
    else
      puts "Ups źle"
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    p = params[:order]
    order = p.nil?||p=="asc" ? :asc : :desc
    @authors=Author.order(name: order)
  end

  def show
    p = params[:order]
    order = p.nil?||p=="asc" ? :asc : :desc
    @author=Author.find(params[:id])
    @books=@author.books.order(title: order)
  end

  def new
    @author = Author.new
  end

  def create
    # render plain: params[:author].inspect
    @author=Author.new(author_params)
    if @author.save
      flash[:notice] = "Author successfully created!"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def edit
    @author=Author.find(params[:id])
  end

  def update
    @author=Author.find(params[:id])
    if(@author.update(author_params))
      flash[:notice] = "Author successfully updated!"
      redirect_to authors_path
    else
      render 'edit'
    end
  end

  def destroy
    @author=Author.find(params[:id])
    @author.destroy
    flash[:notice] = "Author successfully destroyed!"
    redirect_to authors_path
  end

  private
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    p = params[:order]
    order = p.nil?||p=="asc" ? :asc : :desc
    @books=Book.all.order(title: order)
  end

  def show
    @book=Book.find(params[:id])
  end

  def new
    @author_name = params[:author_id].nil? ? nil : Author.find(params[:author_id]).name
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    name = author_params[:author_name]
    @author = Author.where(name: name).first

    @book.author = @author

    if @book.save
      flash[:notice] = "Book successfully created!"
      redirect_to author_path(@author)
    else
      render 'new'
    end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if(@book.update(book_params))
      flash[:notice] = "Book successfully updated!"
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book successfully destroyed!"
    redirect_to author_books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :description)
    end

    def author_params
      params.require(:book).permit(:author_name)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book.comments.create(comment_params)
    redirect_to book_path(@book)
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :commenter)
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  def index
  end

  def basics
  end

  def migrations
  end

  def validations
  end

  def callbacks
  end

  def associations
  end

  def interface
  end

  def ocontroller
  end

  def rrout
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>

<%= form_with(model: @account, local: true) do |form| %>

<% if @account.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@account.errors.count, "error") %> prohibited
      this author from being saved:
    </h2>
    <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/accounts/show.html.erb
<h2>User Account</h2>


<ul>
  <li>Name: <%= current_user.name %></li>
  <li>Gold: <%= current_user.gold %></li>
  <li>Silver: <%= current_user.silver %></li>
  <li>Wood: <%= current_user.wood %></li>
</ul>

app/views/articles/index.html.erb
<h2>Articles</h2>

<%= link_to 'New article', new_article_path %>

<ul>
<% @articles.each do |a| %>
  <li>
    <p>
      <%= link_to a.title, article_path(a) %>(<%= a.user.email %>)
    </p>
  </li>
<% end %>
</ul>

app/views/articles/new.html.erb
<h2>Create New Article</h2>

<%= form_with(model: @article,  local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h2>
  <%= @article.title %>
</h2>


<p>Autor: <%= @article.user.email %></p>

<p>
  <%= @article.text %>
</p>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= form_with(model: @author, local: true) do |form| %>

<% if @author.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@author.errors.count, "error") %> prohibited
      this author from being saved:
    </h2>
    <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<p>
  <%= link_to 'Add author', new_author_path %> |
  Order:
  <% if params[:order].nil?||params[:order]=="asc" %>
    <%= link_to 'Desc', authors_path(order: :desc) %>
  <% else %>
    <%= link_to 'Asc', authors_path(order: :asc) %>
  <% end %>

</p>

<ul>
<% @authors.each do |a| %>
  <li>
    <%= link_to a.name, author_path(a) %> |
    <%= link_to 'Edit', edit_author_path(a) %> |
    <%= link_to 'Destroy', author_path(a),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  </li>
<% end %>
</ul>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_with(model: @author,  local: true) do |form| %>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/authors/show.html.erb
<h2><%= @author.name %></h2>

<%= link_to "Add Book", new_book_path(author_id: @author.id) %>

<% if params[:order].nil?||params[:order]=="asc" %>
  <%= link_to 'Desc', author_path(@author,order: :desc) %>
<% else %>
  <%= link_to 'Asc', author_path(@author, order: :asc) %>
<% end %>

<ul>
<% @books.each do |book| %>
  <li>
    <%= link_to book.title, book_path(book) %>
  </li>
<% end %>
</ul>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_with(model: @book, local: true) do |form| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@book.errors.count, "error") %> prohibited
      this author from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</p>

<p>
  <%= form.label :description %><br>
  <%= form.text_area :description %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

<%= link_to 'Authors', authors_path %>

app/views/books/index.html.erb
<h2>Books</h2>


<p>
  <%= link_to 'Add book', new_book_path(@author) %> |
  Order:
  <% if params[:order].nil?||params[:order]=="asc" %>
    <%= link_to 'Desc', books_path(order: :desc) %>
  <% else %>
    <%= link_to 'Asc', books_path(order: :asc) %>
  <% end %>
</p>

<% if @books.any? %>
  <ul>
  <% @books.each do |b| %>
    <li>
      <%= link_to b.title, book_path(b) %> |
      <%= link_to 'Edit', edit_book_path(b) %> |
      <%= link_to 'Destroy', b,
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
  </ul>
<% else %>
  <p>No books</p>
<% end %>

app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= form_with scope: :book , url: books_path, local: true do |form| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@book.errors.count, "error") %> prohibited
      this author from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <p>
    <%= form.label :author_name %><br>
    <%= form.text_field :author_name, value: @author_name %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>

<p>Author:
  <%= link_to @book.author.name,
              author_path(@book.author) %></p>

<p>
  <%= @book.description %>
</p>

<h3>Comments</h3>


<ul>
<% @book.comments.each do |cm| %>
  <li><%= cm.commenter %>: <%= cm.body %></li>
<% end %>
</ul>

<h2>Add a comment:</h2>
<%= form_with(model: [ @book, @book.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/guides/abasics.html.erb
<h2>Active Model Basics</h2>

<ul>

  <li>
    <p>
      Active Model to biblioteka zawierająca różne moduły używane do tworzenia klas potrzebujących
      niektórych funkcjonalności Active Record. Moduł AttributeMethods pozwala na dodawanie własnych
      prefiksów i sufiksów do metod klas. Callbacks umożliwia tworzenie callbacków w stylu Active
      Record. Jeżeli klasa posiada metody id i persisted? można w niej użyć modułu Conversion, który
      pozwala na konwertowanie obiektów do innego typu. Obiekt staje się brudny jeżeli jego atrybuty
      zostały zmodyfikowane ale nie zapisane. Moduł Dirty dostarcza metody pozwalające na sprawdzenie
      czy taka sytuacja ma miejsce. Moduł Validations dodaje możliwość walidacji obiektów a Naming
      zawiera funkcje przeznaczone do operacji na nazwach i ścieżkach. ActiveModel::Model umożliwia
      klasie łatwą współpracę z Action Pack i Action View. ActiveModel::Serialization podobnie jak
      ActiveModel::Serializers::JSON to funkcje związane z serializacją obiektu. Moduł integrujący
      obiekt z frameworkiem i18n to ActiveModel::Translation. Metoda human_attribute_name przekształca
      nazwy atrybutów do postaci bardziej zrozumiałej dla człowieka. Odpowiednie definicje znajdują
      w plikach w folderze locales. ActiveModel::Lint::Tests pozwala na sprawdzenie, czy obiekt jest
      zgodny z Active Model API. ActiveModel::SecurePassword umożliwia przechowywanie dowolnego
      hasła w bezpiecznej zaszyfrowanej formie. Aby moduł działał poprawnie konieczne jest użycie w
      aplikacji gema bcrypt. Model powinien mieć metodę akcesora XXX_digest gdzie XXX jest nazwą
      atrybutu hasła. Automatycznie ustawiane są walidacje sprawdzające obecność hasła, jego
      potwierdzenie oraz maksymalną długość wynoszącą 72 znaki.
    </p>
  </li>
  
</ul>

app/views/guides/basics.html.erb
<h2>Active Record Basics</h2>

<ul>

  <li>
    <p>
      Active Record to model w skrócie MVC. To warstwa systemu odpowiedzialna za
      reprezentowanie danych i logiki biznesowej. AR ułatwia tworzenie i używanie
      obiektów, których dane wymagają stałego przechowywania w bazie. AR to dane
      i zachowania związane z tymi danymi. Połączenie logiki z obiektem sprawia,
      że jego użytkownicy będą wiedzieli jak go używać, jak zapisywać i odczytywać
      informacje. ORM łączy obiekty aplikacji z tabelami bazy danych. Dzięki temu
      nie jest konieczne pisanie zapytań SQL. AR to modele i ich dane, powiązania
      między modelami, hierarchie dziedziczenia, sprawdzanie poprawności danych a
      także zorientowane obiektowo działania na bazie danych.
    </p>
  </li>

  <li>
    <p>
      W trakcie pisania aplikacji w innych językach programowania lub frameworkach
      konieczne może być użycie dużej ilości kodu konfiguracyjnego. RoR zakłada,
      że jeśli użytkownik stosuje się do ogólnie przyjętych konwencji nie będzie musiał
      konfigurować zbyt wiele. Poza nielicznymi wyjątkami, konfiguracja aplikacji
      będzie zawsze taka sama. Rails używa konwencji nazw do modeli i bazy danych.
      Chodzi o to że nazwa klasy np Book zostaje ustawiona jako tabela books w bazie.
      Działa to dla różnych słów regularnych i nieregularnych. Kiedy używa się modeli
      z wieloma słowami trzeba użyć CamelCase a nazwa tabeli musi być z undescorami.
      Na przykład klasa BookClub to tabela book_clubs, Deer - deers, Mouse - mice,
      Person - people, LineItem - line_items. Są też konwencje dla kolumn w bazie
      danych. Klucze obce to nazwa_id, item_id, order_id. Klucze główne to domyślnie
      id. Są też inne nazwy kolumn np created_at, updated_at, lock_version, type, count.
      Te opcjonalne nazwy są zarezerwowane przez Active Record dlatego lepiej ich unikać
      i używać innych słów o podobnym znaczeniu.
    </p>
  </li>

  <li>
    <p>
      Aby stworzyć model AR wystarczy klasa dziedzicząca po ApplicationRecord, np
      "class Product < ApplicationRecord". Model będzie mapowany do tabeli products.
      Kolumny dostępne będą jako atrybuty obiektu. Jeżeli tabela powstała przy
      użyciu zapytania "CREATE TABLE products (id int(11) NOT NULL auto_increment,
      name varchar(255),PRIMARY KEY  (id));" będzie można napisać p = Product.new,
      p.name = "Some Book", puts p.name.
    </p>
  </li>

  <li>
    <p>
      Jeżeli używana jest stara baza danych konwencje nazw mogą być w łatwy sposób
      zmienione. Wystarczy użyć metody self.table_name = "my_products" aby zmienic nazwe
      tabeli. W takim przypadku należy też zmienić nazwe klasy z fixturami.
      "set_fixture_class my_products: Product, fixtures :my_products". Można też
      zmienić kolumnę używaną jako klucz główny używając metody "self.primary_key = "product_id"".
    </p>
  </li>

  <li>
    <p>
      CRUD - Obiekty mogą być tworzone z hasza, bloku, albo można ustawiać ich atrybuty
      ręcznie po utworzeniu. Metoda new tworzy nowy obiekt a metoda create tworzy go
      i zapisuje w bazie danych. Np "user = User.create(name: "David", occupation: "Code Artist")".
      Bez zapisywania - "user = User.new, user.name = "David", user.occupation = "Code Artist"".
      Dopiero user.save zapisze obiekt w bazie. Można też użyć bloku "user = User.new do |u|,
      u.name = "David", u.occupation = "Code Artist" end". Odczytywanie, wszyscy użytkownicy -
      "User.all", pierwszy - "User.first",o imieniu 'David' - "david = User.find_by(name: 'David')",
      złożone zapytanie - "users = User.where(name: 'David', occupation: 'Code Artist').order(created_at: :desc)".
      Model można zupdatować np "user = User.find_by(name: 'David'), user.name = 'Dave', user.save".
      Można też użyć metody update, również dla wielu atrybutów "user.update(name: 'Dave')".
      Aby uaktualnić wszystkie rekordy - "User.update_all "max_login_attempts = 3, must_change_password = 'true'"".
      Usuwanie rekordu - "User.destroy", "User.destroy_by(name: 'David')" albo
      "User.destroy_all".
    </p>
  </li>

  <li>
    <p>
      AR pozwala na sprawdzanie poprawnosci danych przed zapisanie w bazie danych.
      Można sprawdzic czy model nie jest pust, czy jest unikalny albo czy ma go
      już w bazie danych. Metody save i update zwracaja false jeżeli model był
      niepoprawny i nie zapisują go w bazie. Są też metody save! i update!
      generujące błąd w przypadku nieprawidłowego modelu. Np jeżeli w modelu User
      "validates :name, presence: true", to dla pustego użytkownika user.save zwróci
      false a user.save! błąd "ActiveRecord::RecordInvalid: Validation failed:
      Name can't be blank".
    </p>
  </li>

  <li>
    <p>
      Callbacki pozwalają na uruchamianie fragmentów programu w różnych momentach
      życia modeli, np kiedy są one tworzone, aktualizowane lub usuwane.
    </p>
  </li>

  <li>
    <p>
      RoR używa specjalnego DSL do zarządzania schematem bazy danych. Migracje są
      przechowywane w plikach wykonywanych na bazie danych, gdzie można użyć Active
      Record przy pomocy rake. RoR śledzi, które pliki zostały użyte na bazie i
      pozwala na cofnięcie dokonanych zmian - rollback. Aby stworzyc tabele należy
      uzyć "rails db:migrate", aby cofnąć zmiany - "rails db:rollback". Pliki migracji
      są niezależne od rodzaju bazy danych, np MySQL, PostgreSQL, Oracle.
    <p>
  </li>

</ul>

app/views/guides/index.html.erb
<h2>Guides Index</h2>

<ol>

  <hr>

  <li>
    <%= link_to 'Active Record Basics', guides_basics_path %>
  </li>

  <li>
    <%= link_to 'Active Record Migrations', guides_migrations_path %>
  </li>

  <li>
    <%= link_to 'Active Record Validations', guides_validations_path %>
  </li>

  <li>
    <%= link_to 'Active Record Callbacks', guides_callbacks_path %>
  </li>

  <li>
    <%= link_to 'Active Record Associations', guides_associations_path %>
  </li>

  <li>
    <%= link_to 'Active Record Interface', guides_interface_path %>
  </li>

  <li>
    <%= link_to 'Active Model Basics', guides_abasics_path %>
  </li>

  <hr>

  <li>
    <%= link_to 'Action View Overview', guides_viewover_path %>
  </li>

  <li>
    <%= link_to 'Layouts and Rendering in Rails', guides_layrender_path %>
  </li>

  <li>
    <%= link_to 'Action View Form Helpers', guides_viewform_path %>
  </li>

  <hr>

  <li>
    <%= link_to 'Action Controller Overview', guides_ocontroller_path %>
  </li>

  <li>
    <%= link_to 'Rails Routing', guides_rrout_path %>
  </li>

  <hr>

</ol>

app/views/guides/viewform.html.erb
<h2>Action View Form Helpers</h2>

<ul>

  <li>
    <p>
      Główny form helper to funkcja form_with bez argumentów. Wygenerowany formularz posiada ukryte
      pole i authenticity_token. Przy pomocy tej funkcji i tag helperów można utworzyć prosty formularz
      wyszukiwania. Popularne helpery to między innymi checkboxy, radio buttony, pola tekstowe,
      pola z hasłami, kolorami, datami itp.
    </p>
  </li>
  
  <li>
    <p>
      Istnieją też helpery tworzące formularze dla modeli - "text_field(:person, :name)". Można też
      zbindować formularz i model używając metody form_with :model. W podobny sposób można użyć
      metody fields_for, na przykład dla powiązanych modeli. Funkcja form_with jest w stanie
      wygenerować formularz na podstawie dostarczonego obiektu. Ścieżki z przestrzeni nazw mogą
      być obsługiwane dzięki przekazaniu opcji :model odpowiednich wartości. Specjalne requesty są
      emulowane dzięki ukrytemu polu _method.
    </p>
  </li>
  
  <li>
    <p>
      Dzięki helperom można w łatwy sposób tworzyć select boxy. Wystarczy użyć funkcji select_tag.
      Opcje mogą posiadać dowolne atrybuty, których wartości przekazywane są jako hashe. Select boxy
      działają również z modelami. Użytecznymi helperami są options_from_collection_for_select
      generujący opcje na podstawie listy obiektów i collection_select tworzący odpowiedniego select
      boxa. Helper time_zone_select pozwala użytkownikowi na wybranie strefy czasowej.
    </p>
  </li>
  
  <li>
    <p>
      Helpery select pozwalają na wygenerowanie tagów związanych z wyborem daty. Podobnym helperem
      przeznaczonym do pracy z modelami jest date_select. Opcje :start_year i :end_year ustawiają
      zakres dostępnych dat. Metoda select_date powinna być stosowana jeśli generowane treści nie
      mają związku z modelami. Do wyświetlania pojedynczych wartości służą metody takie jak select_day,
      select_hour, select_year itp.
    </p>
  </li>
  
  <li>
    <p>
      Podczas uploadowania plików atrybut enctype musi być ustawiony na wartość "multipart/form-data".
      Użycie form_with z parametrem model sprawia, że jest to ustawiane automatycznie. W przeciwnym
      razie należy odpowiednią opcję wybrać samodzielnie. RoR posiada helpery związane z uploadem
      plików. Są to file_field_tag i file_field. W późniejszych operacjach na uploadowanych plikach
      pomocne jest Active Storage.
    </p>
  </li>
  
  <li>
    <p>
      Możliwe jest tworzenie własnych Form Builderów dziedziczących po klasie FormBuilder. Mogą one
      zawierać własne metody helperów np text_field. W przypadku częstego korzystania z buildera
      dobrze jest stworzyć funkcję wykonującą automatycznie potrzebne działania. Z builderów można
      korzystać również podczas wywołań metody render.
    </p>
  </li>
  
  <li>
    <p>
      Struktura hasha z parametrami odpowiada nazwom zmiennych używanych w tagach. Możliwe jest ich
      dowolne zagnieżdżanie. RoR zwykle ignoruje zduplikowane nazwy parametrów. Aby to zmienić należy
      na końcu nazwy pola dodać parę nawiasów kwadratowych. Spowoduje to umieszczenie wartośći z pól
      w jednej tablicy. Wymienione cechy można łączyć tworząc na przykład tablicę hashów. Nie powinno
      stosować się parametrów tablicowych w połączeniu z helperem check_box. Do generowania formularzy
      służą metody form_with i fields_for oraz opcja :index.
    </p>
  </li>
  
  <li>
    <p>
      Form helpery pozwalają na wysyłanie danych do zewnętrznych zasobów. W tym przypadku może być
      konieczne ustawienie wartości authenticity_token helperowi form_with. Jeżeli nie należy tego
      robić powinna zostać wybrana opcja false.
    </p>
  </li>
  
  <li>
    <p>
      Podczas budowania skomplikowanych formularzy przydatna może sie okazać metoda Active Record
      accept_nested_attributes_for. Pozwala ona na tworzenie aktualizowanie i usuwanie odpowiednich
      wartości. Przed modyfikowaniem pól należy zadeklarować parametry jako dozwolone. Opcja
      :allow_destroy pozwala na usuwanie powiązanych obiektów a :reject_if ignoruje pola, które nie
      zostały wypełnione przez użytkownika. RoR nie posiada helperów pozwalających na dynamiczne
      dodawanie pól formularza.
    </p>
  </li>
  
  <li>
    <p>
      Funkcje form_tag i form_for zostały zastąpione przez form_with i są uznawane za przestarzałe.
      Informacje na ich temat można znaleźć w poprzednych wersjach przewodnika.
    </p>
  </li>
  
  
  
</ul>